<?xml version="1.0" encoding="utf-8"?><Database Name="BCTest" Class="LotMapDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=BCTest;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BCTestConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Lots" Member="Lots">
    <Type Name="Lot">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="X_CoOrd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Y_CoOrd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LotNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>